// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mailContracts.proto
// Protobuf Java Version: 4.31.1

package com.digitTwin.lib.contracts;

@com.google.protobuf.Generated
public final class MailContracts {
  private MailContracts() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      MailContracts.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Тип сообщения E-mail
   * </pre>
   *
   * Protobuf enum {@code digittwin.lib.contracts.EmailTypeEnum}
   */
  public enum EmailTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Добавьте другие типы, если нужно
     * </pre>
     *
     * <code>DEFAULT = 0;</code>
     */
    DEFAULT(0),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        EmailTypeEnum.class.getName());
    }
    /**
     * <pre>
     * Добавьте другие типы, если нужно
     * </pre>
     *
     * <code>DEFAULT = 0;</code>
     */
    public static final int DEFAULT_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EmailTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EmailTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmailTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EmailTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmailTypeEnum>() {
            public EmailTypeEnum findValueByNumber(int number) {
              return EmailTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.digitTwin.lib.contracts.MailContracts.getDescriptor().getEnumTypes().get(0);
    }

    private static final EmailTypeEnum[] VALUES = values();

    public static EmailTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EmailTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:digittwin.lib.contracts.EmailTypeEnum)
  }

  public interface EventMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:digittwin.lib.contracts.EventMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Уникальный идентификатор события (GUID как строка)
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * Уникальный идентификатор события (GUID как строка)
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * Дата создания
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 2;</code>
     * @return Whether the created field is set.
     */
    boolean hasCreated();
    /**
     * <pre>
     * Дата создания
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 2;</code>
     * @return The created.
     */
    com.google.protobuf.Timestamp getCreated();
    /**
     * <pre>
     * Дата создания
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder();
  }
  /**
   * <pre>
   * Базовое событие
   * </pre>
   *
   * Protobuf type {@code digittwin.lib.contracts.EventMessage}
   */
  public static final class EventMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:digittwin.lib.contracts.EventMessage)
      EventMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        EventMessage.class.getName());
    }
    // Use EventMessage.newBuilder() to construct.
    private EventMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EventMessage() {
      id_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_EventMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_EventMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitTwin.lib.contracts.MailContracts.EventMessage.class, com.digitTwin.lib.contracts.MailContracts.EventMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <pre>
     * Уникальный идентификатор события (GUID как строка)
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Уникальный идентификатор события (GUID как строка)
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp created_;
    /**
     * <pre>
     * Дата создания
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 2;</code>
     * @return Whether the created field is set.
     */
    @java.lang.Override
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Дата создания
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 2;</code>
     * @return The created.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreated() {
      return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
    }
    /**
     * <pre>
     * Дата создания
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getCreated());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCreated());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.digitTwin.lib.contracts.MailContracts.EventMessage)) {
        return super.equals(obj);
      }
      com.digitTwin.lib.contracts.MailContracts.EventMessage other = (com.digitTwin.lib.contracts.MailContracts.EventMessage) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (hasCreated() != other.hasCreated()) return false;
      if (hasCreated()) {
        if (!getCreated()
            .equals(other.getCreated())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (hasCreated()) {
        hash = (37 * hash) + CREATED_FIELD_NUMBER;
        hash = (53 * hash) + getCreated().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.digitTwin.lib.contracts.MailContracts.EventMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitTwin.lib.contracts.MailContracts.EventMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Базовое событие
     * </pre>
     *
     * Protobuf type {@code digittwin.lib.contracts.EventMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:digittwin.lib.contracts.EventMessage)
        com.digitTwin.lib.contracts.MailContracts.EventMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_EventMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_EventMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitTwin.lib.contracts.MailContracts.EventMessage.class, com.digitTwin.lib.contracts.MailContracts.EventMessage.Builder.class);
      }

      // Construct using com.digitTwin.lib.contracts.MailContracts.EventMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetCreatedFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        created_ = null;
        if (createdBuilder_ != null) {
          createdBuilder_.dispose();
          createdBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_EventMessage_descriptor;
      }

      @java.lang.Override
      public com.digitTwin.lib.contracts.MailContracts.EventMessage getDefaultInstanceForType() {
        return com.digitTwin.lib.contracts.MailContracts.EventMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.digitTwin.lib.contracts.MailContracts.EventMessage build() {
        com.digitTwin.lib.contracts.MailContracts.EventMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.digitTwin.lib.contracts.MailContracts.EventMessage buildPartial() {
        com.digitTwin.lib.contracts.MailContracts.EventMessage result = new com.digitTwin.lib.contracts.MailContracts.EventMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.digitTwin.lib.contracts.MailContracts.EventMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.created_ = createdBuilder_ == null
              ? created_
              : createdBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitTwin.lib.contracts.MailContracts.EventMessage) {
          return mergeFrom((com.digitTwin.lib.contracts.MailContracts.EventMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitTwin.lib.contracts.MailContracts.EventMessage other) {
        if (other == com.digitTwin.lib.contracts.MailContracts.EventMessage.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasCreated()) {
          mergeCreated(other.getCreated());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    internalGetCreatedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * Уникальный идентификатор события (GUID как строка)
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Уникальный идентификатор события (GUID как строка)
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Уникальный идентификатор события (GUID как строка)
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Уникальный идентификатор события (GUID как строка)
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Уникальный идентификатор события (GUID как строка)
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp created_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       * @return Whether the created field is set.
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       * @return The created.
       */
      public com.google.protobuf.Timestamp getCreated() {
        if (createdBuilder_ == null) {
          return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
        } else {
          return createdBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       */
      public Builder setCreated(com.google.protobuf.Timestamp value) {
        if (createdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          created_ = value;
        } else {
          createdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       */
      public Builder setCreated(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdBuilder_ == null) {
          created_ = builderForValue.build();
        } else {
          createdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       */
      public Builder mergeCreated(com.google.protobuf.Timestamp value) {
        if (createdBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            created_ != null &&
            created_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreatedBuilder().mergeFrom(value);
          } else {
            created_ = value;
          }
        } else {
          createdBuilder_.mergeFrom(value);
        }
        if (created_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000002);
        created_ = null;
        if (createdBuilder_ != null) {
          createdBuilder_.dispose();
          createdBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetCreatedFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
        if (createdBuilder_ != null) {
          return createdBuilder_.getMessageOrBuilder();
        } else {
          return created_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : created_;
        }
      }
      /**
       * <pre>
       * Дата создания
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          internalGetCreatedFieldBuilder() {
        if (createdBuilder_ == null) {
          createdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreated(),
                  getParentForChildren(),
                  isClean());
          created_ = null;
        }
        return createdBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:digittwin.lib.contracts.EventMessage)
    }

    // @@protoc_insertion_point(class_scope:digittwin.lib.contracts.EventMessage)
    private static final com.digitTwin.lib.contracts.MailContracts.EventMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitTwin.lib.contracts.MailContracts.EventMessage();
    }

    public static com.digitTwin.lib.contracts.MailContracts.EventMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventMessage>
        PARSER = new com.google.protobuf.AbstractParser<EventMessage>() {
      @java.lang.Override
      public EventMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EventMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.digitTwin.lib.contracts.MailContracts.EventMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BaseMailContractOrBuilder extends
      // @@protoc_insertion_point(interface_extends:digittwin.lib.contracts.BaseMailContract)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Базовое событие
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
     * @return Whether the eventMessage field is set.
     */
    boolean hasEventMessage();
    /**
     * <pre>
     * Базовое событие
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
     * @return The eventMessage.
     */
    com.digitTwin.lib.contracts.MailContracts.EventMessage getEventMessage();
    /**
     * <pre>
     * Базовое событие
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
     */
    com.digitTwin.lib.contracts.MailContracts.EventMessageOrBuilder getEventMessageOrBuilder();

    /**
     * <pre>
     * E-mail адресата
     * </pre>
     *
     * <code>string address = 2;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * E-mail адресата
     * </pre>
     *
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * Тема письма
     * </pre>
     *
     * <code>string subject = 3;</code>
     * @return The subject.
     */
    java.lang.String getSubject();
    /**
     * <pre>
     * Тема письма
     * </pre>
     *
     * <code>string subject = 3;</code>
     * @return The bytes for subject.
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <pre>
     * Тело письма
     * </pre>
     *
     * <code>string body = 4;</code>
     * @return The body.
     */
    java.lang.String getBody();
    /**
     * <pre>
     * Тело письма
     * </pre>
     *
     * <code>string body = 4;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @return A list containing the attachments.
     */
    java.util.List<java.lang.String>
        getAttachmentsList();
    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @return The count of attachments.
     */
    int getAttachmentsCount();
    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @param index The index of the element to return.
     * @return The attachments at the given index.
     */
    java.lang.String getAttachments(int index);
    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the attachments at the given index.
     */
    com.google.protobuf.ByteString
        getAttachmentsBytes(int index);

    /**
     * <pre>
     * Тип сообщения
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * Тип сообщения
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
     * @return The type.
     */
    com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum getType();
  }
  /**
   * <pre>
   * Базовый контракт для E-mail
   * </pre>
   *
   * Protobuf type {@code digittwin.lib.contracts.BaseMailContract}
   */
  public static final class BaseMailContract extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:digittwin.lib.contracts.BaseMailContract)
      BaseMailContractOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        BaseMailContract.class.getName());
    }
    // Use BaseMailContract.newBuilder() to construct.
    private BaseMailContract(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseMailContract() {
      address_ = "";
      subject_ = "";
      body_ = "";
      attachments_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      type_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_BaseMailContract_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_BaseMailContract_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitTwin.lib.contracts.MailContracts.BaseMailContract.class, com.digitTwin.lib.contracts.MailContracts.BaseMailContract.Builder.class);
    }

    private int bitField0_;
    public static final int EVENTMESSAGE_FIELD_NUMBER = 1;
    private com.digitTwin.lib.contracts.MailContracts.EventMessage eventMessage_;
    /**
     * <pre>
     * Базовое событие
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
     * @return Whether the eventMessage field is set.
     */
    @java.lang.Override
    public boolean hasEventMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Базовое событие
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
     * @return The eventMessage.
     */
    @java.lang.Override
    public com.digitTwin.lib.contracts.MailContracts.EventMessage getEventMessage() {
      return eventMessage_ == null ? com.digitTwin.lib.contracts.MailContracts.EventMessage.getDefaultInstance() : eventMessage_;
    }
    /**
     * <pre>
     * Базовое событие
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
     */
    @java.lang.Override
    public com.digitTwin.lib.contracts.MailContracts.EventMessageOrBuilder getEventMessageOrBuilder() {
      return eventMessage_ == null ? com.digitTwin.lib.contracts.MailContracts.EventMessage.getDefaultInstance() : eventMessage_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <pre>
     * E-mail адресата
     * </pre>
     *
     * <code>string address = 2;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * E-mail адресата
     * </pre>
     *
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object subject_ = "";
    /**
     * <pre>
     * Тема письма
     * </pre>
     *
     * <code>string subject = 3;</code>
     * @return The subject.
     */
    @java.lang.Override
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Тема письма
     * </pre>
     *
     * <code>string subject = 3;</code>
     * @return The bytes for subject.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object body_ = "";
    /**
     * <pre>
     * Тело письма
     * </pre>
     *
     * <code>string body = 4;</code>
     * @return The body.
     */
    @java.lang.Override
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Тело письма
     * </pre>
     *
     * <code>string body = 4;</code>
     * @return The bytes for body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACHMENTS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList attachments_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @return A list containing the attachments.
     */
    public com.google.protobuf.ProtocolStringList
        getAttachmentsList() {
      return attachments_;
    }
    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @return The count of attachments.
     */
    public int getAttachmentsCount() {
      return attachments_.size();
    }
    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @param index The index of the element to return.
     * @return The attachments at the given index.
     */
    public java.lang.String getAttachments(int index) {
      return attachments_.get(index);
    }
    /**
     * <pre>
     * Вложения
     * </pre>
     *
     * <code>repeated string attachments = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the attachments at the given index.
     */
    public com.google.protobuf.ByteString
        getAttachmentsBytes(int index) {
      return attachments_.getByteString(index);
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_ = 0;
    /**
     * <pre>
     * Тип сообщения
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Тип сообщения
     * </pre>
     *
     * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
     * @return The type.
     */
    @java.lang.Override public com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum getType() {
      com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum result = com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum.forNumber(type_);
      return result == null ? com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getEventMessage());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, address_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(subject_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, subject_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(body_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, body_);
      }
      for (int i = 0; i < attachments_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, attachments_.getRaw(i));
      }
      if (type_ != com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum.DEFAULT.getNumber()) {
        output.writeEnum(6, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEventMessage());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, address_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(subject_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, subject_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(body_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, body_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < attachments_.size(); i++) {
          dataSize += computeStringSizeNoTag(attachments_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAttachmentsList().size();
      }
      if (type_ != com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum.DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.digitTwin.lib.contracts.MailContracts.BaseMailContract)) {
        return super.equals(obj);
      }
      com.digitTwin.lib.contracts.MailContracts.BaseMailContract other = (com.digitTwin.lib.contracts.MailContracts.BaseMailContract) obj;

      if (hasEventMessage() != other.hasEventMessage()) return false;
      if (hasEventMessage()) {
        if (!getEventMessage()
            .equals(other.getEventMessage())) return false;
      }
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getSubject()
          .equals(other.getSubject())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!getAttachmentsList()
          .equals(other.getAttachmentsList())) return false;
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEventMessage()) {
        hash = (37 * hash) + EVENTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getEventMessage().hashCode();
      }
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      if (getAttachmentsCount() > 0) {
        hash = (37 * hash) + ATTACHMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAttachmentsList().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitTwin.lib.contracts.MailContracts.BaseMailContract prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Базовый контракт для E-mail
     * </pre>
     *
     * Protobuf type {@code digittwin.lib.contracts.BaseMailContract}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:digittwin.lib.contracts.BaseMailContract)
        com.digitTwin.lib.contracts.MailContracts.BaseMailContractOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_BaseMailContract_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_BaseMailContract_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitTwin.lib.contracts.MailContracts.BaseMailContract.class, com.digitTwin.lib.contracts.MailContracts.BaseMailContract.Builder.class);
      }

      // Construct using com.digitTwin.lib.contracts.MailContracts.BaseMailContract.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetEventMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        eventMessage_ = null;
        if (eventMessageBuilder_ != null) {
          eventMessageBuilder_.dispose();
          eventMessageBuilder_ = null;
        }
        address_ = "";
        subject_ = "";
        body_ = "";
        attachments_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        type_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitTwin.lib.contracts.MailContracts.internal_static_digittwin_lib_contracts_BaseMailContract_descriptor;
      }

      @java.lang.Override
      public com.digitTwin.lib.contracts.MailContracts.BaseMailContract getDefaultInstanceForType() {
        return com.digitTwin.lib.contracts.MailContracts.BaseMailContract.getDefaultInstance();
      }

      @java.lang.Override
      public com.digitTwin.lib.contracts.MailContracts.BaseMailContract build() {
        com.digitTwin.lib.contracts.MailContracts.BaseMailContract result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.digitTwin.lib.contracts.MailContracts.BaseMailContract buildPartial() {
        com.digitTwin.lib.contracts.MailContracts.BaseMailContract result = new com.digitTwin.lib.contracts.MailContracts.BaseMailContract(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.digitTwin.lib.contracts.MailContracts.BaseMailContract result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.eventMessage_ = eventMessageBuilder_ == null
              ? eventMessage_
              : eventMessageBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.address_ = address_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.subject_ = subject_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.body_ = body_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          attachments_.makeImmutable();
          result.attachments_ = attachments_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.type_ = type_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitTwin.lib.contracts.MailContracts.BaseMailContract) {
          return mergeFrom((com.digitTwin.lib.contracts.MailContracts.BaseMailContract)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitTwin.lib.contracts.MailContracts.BaseMailContract other) {
        if (other == com.digitTwin.lib.contracts.MailContracts.BaseMailContract.getDefaultInstance()) return this;
        if (other.hasEventMessage()) {
          mergeEventMessage(other.getEventMessage());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.attachments_.isEmpty()) {
          if (attachments_.isEmpty()) {
            attachments_ = other.attachments_;
            bitField0_ |= 0x00000010;
          } else {
            ensureAttachmentsIsMutable();
            attachments_.addAll(other.attachments_);
          }
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetEventMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                subject_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                body_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureAttachmentsIsMutable();
                attachments_.add(s);
                break;
              } // case 42
              case 48: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.digitTwin.lib.contracts.MailContracts.EventMessage eventMessage_;
      private com.google.protobuf.SingleFieldBuilder<
          com.digitTwin.lib.contracts.MailContracts.EventMessage, com.digitTwin.lib.contracts.MailContracts.EventMessage.Builder, com.digitTwin.lib.contracts.MailContracts.EventMessageOrBuilder> eventMessageBuilder_;
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       * @return Whether the eventMessage field is set.
       */
      public boolean hasEventMessage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       * @return The eventMessage.
       */
      public com.digitTwin.lib.contracts.MailContracts.EventMessage getEventMessage() {
        if (eventMessageBuilder_ == null) {
          return eventMessage_ == null ? com.digitTwin.lib.contracts.MailContracts.EventMessage.getDefaultInstance() : eventMessage_;
        } else {
          return eventMessageBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       */
      public Builder setEventMessage(com.digitTwin.lib.contracts.MailContracts.EventMessage value) {
        if (eventMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventMessage_ = value;
        } else {
          eventMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       */
      public Builder setEventMessage(
          com.digitTwin.lib.contracts.MailContracts.EventMessage.Builder builderForValue) {
        if (eventMessageBuilder_ == null) {
          eventMessage_ = builderForValue.build();
        } else {
          eventMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       */
      public Builder mergeEventMessage(com.digitTwin.lib.contracts.MailContracts.EventMessage value) {
        if (eventMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            eventMessage_ != null &&
            eventMessage_ != com.digitTwin.lib.contracts.MailContracts.EventMessage.getDefaultInstance()) {
            getEventMessageBuilder().mergeFrom(value);
          } else {
            eventMessage_ = value;
          }
        } else {
          eventMessageBuilder_.mergeFrom(value);
        }
        if (eventMessage_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       */
      public Builder clearEventMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventMessage_ = null;
        if (eventMessageBuilder_ != null) {
          eventMessageBuilder_.dispose();
          eventMessageBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       */
      public com.digitTwin.lib.contracts.MailContracts.EventMessage.Builder getEventMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetEventMessageFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       */
      public com.digitTwin.lib.contracts.MailContracts.EventMessageOrBuilder getEventMessageOrBuilder() {
        if (eventMessageBuilder_ != null) {
          return eventMessageBuilder_.getMessageOrBuilder();
        } else {
          return eventMessage_ == null ?
              com.digitTwin.lib.contracts.MailContracts.EventMessage.getDefaultInstance() : eventMessage_;
        }
      }
      /**
       * <pre>
       * Базовое событие
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EventMessage eventMessage = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.digitTwin.lib.contracts.MailContracts.EventMessage, com.digitTwin.lib.contracts.MailContracts.EventMessage.Builder, com.digitTwin.lib.contracts.MailContracts.EventMessageOrBuilder> 
          internalGetEventMessageFieldBuilder() {
        if (eventMessageBuilder_ == null) {
          eventMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.digitTwin.lib.contracts.MailContracts.EventMessage, com.digitTwin.lib.contracts.MailContracts.EventMessage.Builder, com.digitTwin.lib.contracts.MailContracts.EventMessageOrBuilder>(
                  getEventMessage(),
                  getParentForChildren(),
                  isClean());
          eventMessage_ = null;
        }
        return eventMessageBuilder_;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * E-mail адресата
       * </pre>
       *
       * <code>string address = 2;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * E-mail адресата
       * </pre>
       *
       * <code>string address = 2;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * E-mail адресата
       * </pre>
       *
       * <code>string address = 2;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * E-mail адресата
       * </pre>
       *
       * <code>string address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * E-mail адресата
       * </pre>
       *
       * <code>string address = 2;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object subject_ = "";
      /**
       * <pre>
       * Тема письма
       * </pre>
       *
       * <code>string subject = 3;</code>
       * @return The subject.
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Тема письма
       * </pre>
       *
       * <code>string subject = 3;</code>
       * @return The bytes for subject.
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Тема письма
       * </pre>
       *
       * <code>string subject = 3;</code>
       * @param value The subject to set.
       * @return This builder for chaining.
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        subject_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тема письма
       * </pre>
       *
       * <code>string subject = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubject() {
        subject_ = getDefaultInstance().getSubject();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тема письма
       * </pre>
       *
       * <code>string subject = 3;</code>
       * @param value The bytes for subject to set.
       * @return This builder for chaining.
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        subject_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <pre>
       * Тело письма
       * </pre>
       *
       * <code>string body = 4;</code>
       * @return The body.
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Тело письма
       * </pre>
       *
       * <code>string body = 4;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Тело письма
       * </pre>
       *
       * <code>string body = 4;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        body_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тело письма
       * </pre>
       *
       * <code>string body = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        body_ = getDefaultInstance().getBody();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тело письма
       * </pre>
       *
       * <code>string body = 4;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        body_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList attachments_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureAttachmentsIsMutable() {
        if (!attachments_.isModifiable()) {
          attachments_ = new com.google.protobuf.LazyStringArrayList(attachments_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @return A list containing the attachments.
       */
      public com.google.protobuf.ProtocolStringList
          getAttachmentsList() {
        attachments_.makeImmutable();
        return attachments_;
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @return The count of attachments.
       */
      public int getAttachmentsCount() {
        return attachments_.size();
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @param index The index of the element to return.
       * @return The attachments at the given index.
       */
      public java.lang.String getAttachments(int index) {
        return attachments_.get(index);
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the attachments at the given index.
       */
      public com.google.protobuf.ByteString
          getAttachmentsBytes(int index) {
        return attachments_.getByteString(index);
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @param index The index to set the value at.
       * @param value The attachments to set.
       * @return This builder for chaining.
       */
      public Builder setAttachments(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAttachmentsIsMutable();
        attachments_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @param value The attachments to add.
       * @return This builder for chaining.
       */
      public Builder addAttachments(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAttachmentsIsMutable();
        attachments_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @param values The attachments to add.
       * @return This builder for chaining.
       */
      public Builder addAllAttachments(
          java.lang.Iterable<java.lang.String> values) {
        ensureAttachmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attachments_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttachments() {
        attachments_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Вложения
       * </pre>
       *
       * <code>repeated string attachments = 5;</code>
       * @param value The bytes of the attachments to add.
       * @return This builder for chaining.
       */
      public Builder addAttachmentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureAttachmentsIsMutable();
        attachments_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * Тип сообщения
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * Тип сообщения
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тип сообщения
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum getType() {
        com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum result = com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum.forNumber(type_);
        return result == null ? com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Тип сообщения
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.digitTwin.lib.contracts.MailContracts.EmailTypeEnum value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000020;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Тип сообщения
       * </pre>
       *
       * <code>.digittwin.lib.contracts.EmailTypeEnum type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:digittwin.lib.contracts.BaseMailContract)
    }

    // @@protoc_insertion_point(class_scope:digittwin.lib.contracts.BaseMailContract)
    private static final com.digitTwin.lib.contracts.MailContracts.BaseMailContract DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitTwin.lib.contracts.MailContracts.BaseMailContract();
    }

    public static com.digitTwin.lib.contracts.MailContracts.BaseMailContract getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMailContract>
        PARSER = new com.google.protobuf.AbstractParser<BaseMailContract>() {
      @java.lang.Override
      public BaseMailContract parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BaseMailContract> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMailContract> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.digitTwin.lib.contracts.MailContracts.BaseMailContract getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_digittwin_lib_contracts_EventMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_digittwin_lib_contracts_EventMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_digittwin_lib_contracts_BaseMailContract_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_digittwin_lib_contracts_BaseMailContract_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023mailContracts.proto\022\027digittwin.lib.con" +
      "tracts\032\037google/protobuf/timestamp.proto\"" +
      "G\n\014EventMessage\022\n\n\002id\030\001 \001(\t\022+\n\007created\030\002" +
      " \001(\0132\032.google.protobuf.Timestamp\"\312\001\n\020Bas" +
      "eMailContract\022;\n\014eventMessage\030\001 \001(\0132%.di" +
      "gittwin.lib.contracts.EventMessage\022\017\n\007ad" +
      "dress\030\002 \001(\t\022\017\n\007subject\030\003 \001(\t\022\014\n\004body\030\004 \001" +
      "(\t\022\023\n\013attachments\030\005 \003(\t\0224\n\004type\030\006 \001(\0162&." +
      "digittwin.lib.contracts.EmailTypeEnum*\034\n" +
      "\rEmailTypeEnum\022\013\n\007DEFAULT\020\000B7\n\033com.digit" +
      "Twin.lib.contracts\252\002\027DigitTwin.Lib.Contr" +
      "actsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_digittwin_lib_contracts_EventMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_digittwin_lib_contracts_EventMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_digittwin_lib_contracts_EventMessage_descriptor,
        new java.lang.String[] { "Id", "Created", });
    internal_static_digittwin_lib_contracts_BaseMailContract_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_digittwin_lib_contracts_BaseMailContract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_digittwin_lib_contracts_BaseMailContract_descriptor,
        new java.lang.String[] { "EventMessage", "Address", "Subject", "Body", "Attachments", "Type", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
