# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mailContracts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mailContracts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mailContracts.proto\x12\x17\x64igittwin.lib.contracts\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n\x0c\x45ventMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x07\x63reated\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xca\x01\n\x10\x42\x61seMailContract\x12;\n\x0c\x65ventMessage\x18\x01 \x01(\x0b\x32%.digittwin.lib.contracts.EventMessage\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x13\n\x0b\x61ttachments\x18\x05 \x03(\t\x12\x34\n\x04type\x18\x06 \x01(\x0e\x32&.digittwin.lib.contracts.EmailTypeEnum*\x1c\n\rEmailTypeEnum\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x42\x37\n\x1b\x63om.digitTwin.lib.contracts\xaa\x02\x17\x44igitTwin.Lib.Contractsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mailContracts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.digitTwin.lib.contracts\252\002\027DigitTwin.Lib.Contracts'
  _globals['_EMAILTYPEENUM']._serialized_start=359
  _globals['_EMAILTYPEENUM']._serialized_end=387
  _globals['_EVENTMESSAGE']._serialized_start=81
  _globals['_EVENTMESSAGE']._serialized_end=152
  _globals['_BASEMAILCONTRACT']._serialized_start=155
  _globals['_BASEMAILCONTRACT']._serialized_end=357
# @@protoc_insertion_point(module_scope)
