// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: organizationContracts.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DigitTwin.Lib.Contracts {

  /// <summary>Holder for reflection information generated from organizationContracts.proto</summary>
  public static partial class OrganizationContractsReflection {

    #region Descriptor
    /// <summary>File descriptor for organizationContracts.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrganizationContractsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtvcmdhbml6YXRpb25Db250cmFjdHMucHJvdG8SF2RpZ2l0dHdpbi5saWIu",
            "Y29udHJhY3RzIsMBChxPcmdhbml6YXRpb25DcmVhdGVSZXF1ZXN0RHRvEhEK",
            "CXNob3J0TmFtZRgBIAEoCRIQCghmdWxsTmFtZRgCIAEoCRILCgNpbm4YAyAB",
            "KAkSCwoDa3BwGAQgASgJEgwKBG9ncm4YBSABKAkSEwoLZmFjdEFkZHJlc3MY",
            "BiABKAkSDwoHYWRkcmVzcxgHIAEoCRIPCgdhY2NvdW50GAggASgJEh8KF2Nv",
            "cnJlc3BvbmRlbnRpYWxBY2NvdW50GAkgASgJIsIBCg9Pcmdhbml6YXRpb25E",
            "dG8SCgoCaWQYASABKAkSEQoJc2hvcnROYW1lGAIgASgJEhAKCGZ1bGxOYW1l",
            "GAMgASgJEgsKA2lubhgEIAEoCRILCgNrcHAYBSABKAkSDAoEb2dybhgGIAEo",
            "CRITCgtmYWN0QWRkcmVzcxgHIAEoCRIPCgdhZGRyZXNzGAggASgJEg8KB2Fj",
            "Y291bnQYCSABKAkSHwoXY29ycmVzcG9uZGVudGlhbEFjY291bnQYCiABKAlC",
            "NwobY29tLmRpZ2l0VHdpbi5saWIuY29udHJhY3RzqgIXRGlnaXRUd2luLkxp",
            "Yi5Db250cmFjdHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DigitTwin.Lib.Contracts.OrganizationCreateRequestDto), global::DigitTwin.Lib.Contracts.OrganizationCreateRequestDto.Parser, new[]{ "ShortName", "FullName", "Inn", "Kpp", "Ogrn", "FactAddress", "Address", "Account", "CorrespondentialAccount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DigitTwin.Lib.Contracts.OrganizationDto), global::DigitTwin.Lib.Contracts.OrganizationDto.Parser, new[]{ "Id", "ShortName", "FullName", "Inn", "Kpp", "Ogrn", "FactAddress", "Address", "Account", "CorrespondentialAccount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Запрос на создание организации
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OrganizationCreateRequestDto : pb::IMessage<OrganizationCreateRequestDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrganizationCreateRequestDto> _parser = new pb::MessageParser<OrganizationCreateRequestDto>(() => new OrganizationCreateRequestDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrganizationCreateRequestDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DigitTwin.Lib.Contracts.OrganizationContractsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationCreateRequestDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationCreateRequestDto(OrganizationCreateRequestDto other) : this() {
      shortName_ = other.shortName_;
      fullName_ = other.fullName_;
      inn_ = other.inn_;
      kpp_ = other.kpp_;
      ogrn_ = other.ogrn_;
      factAddress_ = other.factAddress_;
      address_ = other.address_;
      account_ = other.account_;
      correspondentialAccount_ = other.correspondentialAccount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationCreateRequestDto Clone() {
      return new OrganizationCreateRequestDto(this);
    }

    /// <summary>Field number for the "shortName" field.</summary>
    public const int ShortNameFieldNumber = 1;
    private string shortName_ = "";
    /// <summary>
    /// Короткое название организации
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ShortName {
      get { return shortName_; }
      set {
        shortName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fullName" field.</summary>
    public const int FullNameFieldNumber = 2;
    private string fullName_ = "";
    /// <summary>
    /// Полное название организации
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FullName {
      get { return fullName_; }
      set {
        fullName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inn" field.</summary>
    public const int InnFieldNumber = 3;
    private string inn_ = "";
    /// <summary>
    /// ИНН
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Inn {
      get { return inn_; }
      set {
        inn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kpp" field.</summary>
    public const int KppFieldNumber = 4;
    private string kpp_ = "";
    /// <summary>
    /// КПП
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Kpp {
      get { return kpp_; }
      set {
        kpp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ogrn" field.</summary>
    public const int OgrnFieldNumber = 5;
    private string ogrn_ = "";
    /// <summary>
    /// ОГРН
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ogrn {
      get { return ogrn_; }
      set {
        ogrn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "factAddress" field.</summary>
    public const int FactAddressFieldNumber = 6;
    private string factAddress_ = "";
    /// <summary>
    /// Фактический адрес
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FactAddress {
      get { return factAddress_; }
      set {
        factAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 7;
    private string address_ = "";
    /// <summary>
    /// Юридический адрес
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Address {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 8;
    private string account_ = "";
    /// <summary>
    /// Рассчетный счет
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "correspondentialAccount" field.</summary>
    public const int CorrespondentialAccountFieldNumber = 9;
    private string correspondentialAccount_ = "";
    /// <summary>
    /// Кореспондентский счет
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CorrespondentialAccount {
      get { return correspondentialAccount_; }
      set {
        correspondentialAccount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrganizationCreateRequestDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrganizationCreateRequestDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShortName != other.ShortName) return false;
      if (FullName != other.FullName) return false;
      if (Inn != other.Inn) return false;
      if (Kpp != other.Kpp) return false;
      if (Ogrn != other.Ogrn) return false;
      if (FactAddress != other.FactAddress) return false;
      if (Address != other.Address) return false;
      if (Account != other.Account) return false;
      if (CorrespondentialAccount != other.CorrespondentialAccount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ShortName.Length != 0) hash ^= ShortName.GetHashCode();
      if (FullName.Length != 0) hash ^= FullName.GetHashCode();
      if (Inn.Length != 0) hash ^= Inn.GetHashCode();
      if (Kpp.Length != 0) hash ^= Kpp.GetHashCode();
      if (Ogrn.Length != 0) hash ^= Ogrn.GetHashCode();
      if (FactAddress.Length != 0) hash ^= FactAddress.GetHashCode();
      if (Address.Length != 0) hash ^= Address.GetHashCode();
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (CorrespondentialAccount.Length != 0) hash ^= CorrespondentialAccount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ShortName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ShortName);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullName);
      }
      if (Inn.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Inn);
      }
      if (Kpp.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Kpp);
      }
      if (Ogrn.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Ogrn);
      }
      if (FactAddress.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FactAddress);
      }
      if (Address.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Address);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Account);
      }
      if (CorrespondentialAccount.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(CorrespondentialAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ShortName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ShortName);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullName);
      }
      if (Inn.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Inn);
      }
      if (Kpp.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Kpp);
      }
      if (Ogrn.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Ogrn);
      }
      if (FactAddress.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FactAddress);
      }
      if (Address.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Address);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Account);
      }
      if (CorrespondentialAccount.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(CorrespondentialAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ShortName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShortName);
      }
      if (FullName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullName);
      }
      if (Inn.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Inn);
      }
      if (Kpp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Kpp);
      }
      if (Ogrn.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ogrn);
      }
      if (FactAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FactAddress);
      }
      if (Address.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
      }
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (CorrespondentialAccount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorrespondentialAccount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrganizationCreateRequestDto other) {
      if (other == null) {
        return;
      }
      if (other.ShortName.Length != 0) {
        ShortName = other.ShortName;
      }
      if (other.FullName.Length != 0) {
        FullName = other.FullName;
      }
      if (other.Inn.Length != 0) {
        Inn = other.Inn;
      }
      if (other.Kpp.Length != 0) {
        Kpp = other.Kpp;
      }
      if (other.Ogrn.Length != 0) {
        Ogrn = other.Ogrn;
      }
      if (other.FactAddress.Length != 0) {
        FactAddress = other.FactAddress;
      }
      if (other.Address.Length != 0) {
        Address = other.Address;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.CorrespondentialAccount.Length != 0) {
        CorrespondentialAccount = other.CorrespondentialAccount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ShortName = input.ReadString();
            break;
          }
          case 18: {
            FullName = input.ReadString();
            break;
          }
          case 26: {
            Inn = input.ReadString();
            break;
          }
          case 34: {
            Kpp = input.ReadString();
            break;
          }
          case 42: {
            Ogrn = input.ReadString();
            break;
          }
          case 50: {
            FactAddress = input.ReadString();
            break;
          }
          case 58: {
            Address = input.ReadString();
            break;
          }
          case 66: {
            Account = input.ReadString();
            break;
          }
          case 74: {
            CorrespondentialAccount = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ShortName = input.ReadString();
            break;
          }
          case 18: {
            FullName = input.ReadString();
            break;
          }
          case 26: {
            Inn = input.ReadString();
            break;
          }
          case 34: {
            Kpp = input.ReadString();
            break;
          }
          case 42: {
            Ogrn = input.ReadString();
            break;
          }
          case 50: {
            FactAddress = input.ReadString();
            break;
          }
          case 58: {
            Address = input.ReadString();
            break;
          }
          case 66: {
            Account = input.ReadString();
            break;
          }
          case 74: {
            CorrespondentialAccount = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Организация
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OrganizationDto : pb::IMessage<OrganizationDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrganizationDto> _parser = new pb::MessageParser<OrganizationDto>(() => new OrganizationDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrganizationDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DigitTwin.Lib.Contracts.OrganizationContractsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationDto(OrganizationDto other) : this() {
      id_ = other.id_;
      shortName_ = other.shortName_;
      fullName_ = other.fullName_;
      inn_ = other.inn_;
      kpp_ = other.kpp_;
      ogrn_ = other.ogrn_;
      factAddress_ = other.factAddress_;
      address_ = other.address_;
      account_ = other.account_;
      correspondentialAccount_ = other.correspondentialAccount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrganizationDto Clone() {
      return new OrganizationDto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// ИД (GUID в виде строки)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "shortName" field.</summary>
    public const int ShortNameFieldNumber = 2;
    private string shortName_ = "";
    /// <summary>
    /// Короткое название организации
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ShortName {
      get { return shortName_; }
      set {
        shortName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fullName" field.</summary>
    public const int FullNameFieldNumber = 3;
    private string fullName_ = "";
    /// <summary>
    /// Полное название организации
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FullName {
      get { return fullName_; }
      set {
        fullName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inn" field.</summary>
    public const int InnFieldNumber = 4;
    private string inn_ = "";
    /// <summary>
    /// ИНН
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Inn {
      get { return inn_; }
      set {
        inn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kpp" field.</summary>
    public const int KppFieldNumber = 5;
    private string kpp_ = "";
    /// <summary>
    /// КПП
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Kpp {
      get { return kpp_; }
      set {
        kpp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ogrn" field.</summary>
    public const int OgrnFieldNumber = 6;
    private string ogrn_ = "";
    /// <summary>
    /// ОГРН
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ogrn {
      get { return ogrn_; }
      set {
        ogrn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "factAddress" field.</summary>
    public const int FactAddressFieldNumber = 7;
    private string factAddress_ = "";
    /// <summary>
    /// Фактический адрес
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FactAddress {
      get { return factAddress_; }
      set {
        factAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 8;
    private string address_ = "";
    /// <summary>
    /// Юридический адрес
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Address {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 9;
    private string account_ = "";
    /// <summary>
    /// Рассчетный счет
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "correspondentialAccount" field.</summary>
    public const int CorrespondentialAccountFieldNumber = 10;
    private string correspondentialAccount_ = "";
    /// <summary>
    /// Кореспондентский счет
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CorrespondentialAccount {
      get { return correspondentialAccount_; }
      set {
        correspondentialAccount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrganizationDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrganizationDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ShortName != other.ShortName) return false;
      if (FullName != other.FullName) return false;
      if (Inn != other.Inn) return false;
      if (Kpp != other.Kpp) return false;
      if (Ogrn != other.Ogrn) return false;
      if (FactAddress != other.FactAddress) return false;
      if (Address != other.Address) return false;
      if (Account != other.Account) return false;
      if (CorrespondentialAccount != other.CorrespondentialAccount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (ShortName.Length != 0) hash ^= ShortName.GetHashCode();
      if (FullName.Length != 0) hash ^= FullName.GetHashCode();
      if (Inn.Length != 0) hash ^= Inn.GetHashCode();
      if (Kpp.Length != 0) hash ^= Kpp.GetHashCode();
      if (Ogrn.Length != 0) hash ^= Ogrn.GetHashCode();
      if (FactAddress.Length != 0) hash ^= FactAddress.GetHashCode();
      if (Address.Length != 0) hash ^= Address.GetHashCode();
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (CorrespondentialAccount.Length != 0) hash ^= CorrespondentialAccount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ShortName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ShortName);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FullName);
      }
      if (Inn.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Inn);
      }
      if (Kpp.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Kpp);
      }
      if (Ogrn.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Ogrn);
      }
      if (FactAddress.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FactAddress);
      }
      if (Address.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Address);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Account);
      }
      if (CorrespondentialAccount.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(CorrespondentialAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (ShortName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ShortName);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FullName);
      }
      if (Inn.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Inn);
      }
      if (Kpp.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Kpp);
      }
      if (Ogrn.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Ogrn);
      }
      if (FactAddress.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FactAddress);
      }
      if (Address.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Address);
      }
      if (Account.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Account);
      }
      if (CorrespondentialAccount.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(CorrespondentialAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (ShortName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShortName);
      }
      if (FullName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullName);
      }
      if (Inn.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Inn);
      }
      if (Kpp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Kpp);
      }
      if (Ogrn.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ogrn);
      }
      if (FactAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FactAddress);
      }
      if (Address.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
      }
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (CorrespondentialAccount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorrespondentialAccount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrganizationDto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.ShortName.Length != 0) {
        ShortName = other.ShortName;
      }
      if (other.FullName.Length != 0) {
        FullName = other.FullName;
      }
      if (other.Inn.Length != 0) {
        Inn = other.Inn;
      }
      if (other.Kpp.Length != 0) {
        Kpp = other.Kpp;
      }
      if (other.Ogrn.Length != 0) {
        Ogrn = other.Ogrn;
      }
      if (other.FactAddress.Length != 0) {
        FactAddress = other.FactAddress;
      }
      if (other.Address.Length != 0) {
        Address = other.Address;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.CorrespondentialAccount.Length != 0) {
        CorrespondentialAccount = other.CorrespondentialAccount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ShortName = input.ReadString();
            break;
          }
          case 26: {
            FullName = input.ReadString();
            break;
          }
          case 34: {
            Inn = input.ReadString();
            break;
          }
          case 42: {
            Kpp = input.ReadString();
            break;
          }
          case 50: {
            Ogrn = input.ReadString();
            break;
          }
          case 58: {
            FactAddress = input.ReadString();
            break;
          }
          case 66: {
            Address = input.ReadString();
            break;
          }
          case 74: {
            Account = input.ReadString();
            break;
          }
          case 82: {
            CorrespondentialAccount = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            ShortName = input.ReadString();
            break;
          }
          case 26: {
            FullName = input.ReadString();
            break;
          }
          case 34: {
            Inn = input.ReadString();
            break;
          }
          case 42: {
            Kpp = input.ReadString();
            break;
          }
          case 50: {
            Ogrn = input.ReadString();
            break;
          }
          case 58: {
            FactAddress = input.ReadString();
            break;
          }
          case 66: {
            Address = input.ReadString();
            break;
          }
          case 74: {
            Account = input.ReadString();
            break;
          }
          case 82: {
            CorrespondentialAccount = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
